### PR TITLE
Fixed Trade Center Admins

### PR DESCRIPTION
**Pull request by RagePit**
Isn't this a really good pull request?

### CODE REVIEW

**Comment by mcbobby123** [comment]
smh my head

**Comment by RagePit** [comment]
whaaaaaa

**Comment by RagePit** [comment]
look i can spam #programming-discussion

**Comment by RagePit** [comment]
look i can spam #programming-discussion

**Comment by RagePit** [comment]
look i can spam #programming-discussion

**Comment by RagePit** [comment]
look i can spam #programming-discussion

**Comment by RagePit** [comment]
look i can spam #programming-discussion

**Pull request closed without merging**
